### ISSUE TITLE
bus and group, Master not defined

### ISSUE THREAD

**Issue by JZito** [charlieroberts/p5.gibber.js#2]
Trying to use the Bus, routinely getting this error. Here's some slightly modified code from the manual, trying to apply it to gibber for p5

function setup() {
a = Synth().note.seq (Rndi(0,5), 1/2)
b = Pluck().note.seq( Rndi(0,12), 1/8 )
c = FM('bass').note.seq( Rndi(0,12), [1/8,1/16].rnd(1/16,2) )

// add fx to drums and synth but note fm
d = Group( a, b ).fx.add( Distortion(100) )

// reconnect drums to their previous bus
d.free( a )
}
function draw() {

}

Uncaught ReferenceError: Master is not defined p5.gibber.js:8437

**Comment by charlieroberts** [comment]
This is fixed in the repo now, but I'm having a lot of trouble pushing to npm for some reason. Let me know if you still have problems with the version in the repo and I'll keep troubleshooting the npm module. Thanks!
